In [ ]:
import requests  # Esse haam htpp req karte using python
import pandas as pd

In [ ]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=9c3510b4224a5c362c701d95238b950d')
# Output <Response [200]> server Conected sucseefully

In [ ]:
response

In [ ]:
response.json()

In [ ]:
movies_reult = response.json()['results']
movies_reult
# Ye Kaya karega Esse shirf result ko dikhayega

In [11]:
df = pd.DataFrame(movies_reult)
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",617.3077,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,7.913,817
1,False,/laR2dpcNpbv83jdlRUNAYPPjH90.jpg,"[28, 14, 12]",931285,Mortal Kombat II,en,Mortal Kombat II,The fan favorite champions—now joined by Johnn...,536.6859,/hwRdDFIhaEmpRgoki805YvyyjZf.jpg,2026-05-06,False,False,7.987,1427
2,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",512.4438,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.650,2567
3,False,/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg,"[28, 18]",1057265,Peddi,te,పెద్ది,"In 1980s rural Andhra Pradesh, a spirited vill...",361.9352,/kJAJNNBYlbqAcpTDxBNnaILSMTy.jpg,2026-06-03,False,False,6.547,43
4,False,/1eAuwNBy34kkM3xkl202z4f1NiI.jpg,"[28, 14]",1367220,Karuppu,ta,கருப்பு,"In a world where justice falters, guardian dei...",413.7865,/4KZXlZ5tTT6ghbW77gS4hSLkCd7.jpg,2026-05-14,False,False,7.059,17
5,False,/7uXzE0ZBkbAeKylOz7cUQF4Yw75.jpg,[18],879945,The Unknown Man,nl,L'homme inconnu,"Louis, a Flemish writer, decides to isolate hi...",378.8827,/4TpBhdaSl5ALHbgeaYOLF8Q3haz.jpg,2021-10-16,False,False,7.800,9
6,False,/l5QgEvlfK6eHPM4YPEk7AArXmh8.jpg,"[10749, 35]",1308553,Hai Jawani Toh Ishq Hona Hai,hi,है जवानी तो इश्क होना है,When Jass leaves his marriage over conflicting...,289.6886,/vmlJvz6qVzYgei2V74GvnmcuQfW.jpg,2026-06-04,False,False,5.471,17
7,False,/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg,"[53, 878, 9648]",1275779,Disclosure Day,en,Disclosure Day,"If you found out we weren’t alone, if someone ...",326.4035,/3o5YPjDGDTcTDL5ftDA9NwN9dLd.jpg,2026-06-10,False,False,6.778,481
8,False,/A2tzVTVtnTvpji96IZmleN78KKv.jpg,"[27, 35]",1239134,Bhooth Bangla,hi,भूत बंगला,A man inherits a palace in rural Mangalpur and...,337.3635,/79RBp8afL4u4z3nVGR78z6eIvBB.jpg,2026-04-16,False,False,5.500,20
9,False,/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg,"[10751, 35, 12, 14, 16]",1226863,The Super Mario Galaxy Movie,en,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,243.6128,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,2026-04-01,False,False,8.193,2654
10,False,/6zg7A9ICOthNR2TSXlT51KvXrsA.jpg,"[28, 12, 878]",1228710,The Mandalorian and Grogu,en,The Mandalorian and Grogu,"The evil Empire has fallen, and Imperial warlo...",239.2479,/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg,2026-05-20,False,False,6.766,481
11,False,/emK2hOB6ACiExT0lNLog9lAmMFL.jpg,"[18, 10749]",1226293,Salitan,tl,Salitan,A suspicious wife follows her husband in Bali....,231.5883,/rMgG7cWuq9O6zhhLs2CbqIKVA8V.jpg,2024-02-16,False,False,4.714,7
12,False,None,[18],1604143,나는 신혼 너는 재혼,ko,나는 신혼 너는 재혼,,274.1095,/wTFF1SFTDYL7M1yWjY0K8Ga5pZS.jpg,2021-08-12,False,False,0.000,0
13,False,/l1nekhf05HS5OpBr0vRqcD3NxoS.jpg,"[36, 80, 28, 14]",1103473,KD – The Devil,kn,ಕೆಡಿ - ದಿ ಡೆವಿಲ್,"In the early 1970s, a petty criminal Kaali unw...",207.3802,/nEuEMJrnLBneE9tJlmzbhCFLu95.jpg,2026-04-30,False,False,7.500,2
14,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,Your Heart Will Be Broken,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,254.0422,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,False,False,6.913,92
15,False,/krhj4Fhb0G3QCmyBtEADxgFFmRX.jpg,"[18, 10749]",11012,Damage,en,Damage,The life of a respected British politician at ...,184.6617,/alf3JOPP7EYP0iO24gwe5YfRnqo.jpg,1992-12-02,False,False,6.600,689
16,False,/xugEpZk9YQ0DIz1aFvH5HGkqpZK.jpg,"[27, 9648]",1304313,Lee Cronin's The Mummy,en,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,168.1853,/1q308iixueCU4pFtSYugNOevtNx.jpg,2026-04-15,False,False,8.048,1861
17,False,/jPr9Id0f3knF82ETEBGPpMhXj4M.jpg,"[80, 53]",912378,Dridam,ml,ദൃഢം,A police officer arrives at a seemingly peacef...,175.7922,/fXSdAujfiRRW6LqekN4FvFQidh3.jpg,2026-05-08,False,False,7.000,1
18,False,/piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg,"[28, 14, 878]",454639,Masters of the Universe,en,Masters of the Universe,"After being separated for 15 years, the Sword ...",152.4585,/3YMd9Ogae4rDKLWuAZFuse9xhc5.jpg,2026-06-03,False,False,7.300,236
19,False,/ew3EqF9VLTxmK64OsHT7p7lr4wT.jpg,"[28, 80]",1280738,The Furious,en,火遮眼,After Wang Wei's daughter is kidnapped by a cr...,173.2088,/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg,2026-06-10,False,False,8.100,39

In [ ]:
# Ab yaha Jo J o mujeh Chahiye Hia Uss emai Nikal Luga 
jo_chahiye = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity','vote_average', 'vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-05-13,617.3077,7.913,817
1,931285,Mortal Kombat II,The fan favorite champions—now joined by Johnn...,2026-05-06,536.6859,7.987,1427
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,512.4438,8.650,2567
3,1057265,Peddi,"In 1980s rural Andhra Pradesh, a spirited vill...",2026-06-03,361.9352,6.547,43
4,1367220,Karuppu,"In a world where justice falters, guardian dei...",2026-05-14,413.7865,7.059,17
5,879945,The Unknown Man,"Louis, a Flemish writer, decides to isolate hi...",2021-10-16,378.8827,7.800,9
6,1308553,Hai Jawani Toh Ishq Hona Hai,When Jass leaves his marriage over conflicting...,2026-06-04,289.6886,5.471,17
7,1275779,Disclosure Day,"If you found out we weren’t alone, if someone ...",2026-06-10,326.4035,6.778,481
8,1239134,Bhooth Bangla,A man inherits a palace in rural Mangalpur and...,2026-04-16,337.3635,5.500,20
9,1226863,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,2026-04-01,243.6128,8.193,2654
10,1228710,The Mandalorian and Grogu,"The evil Empire has fallen, and Imperial warlo...",2026-05-20,239.2479,6.766,481
11,1226293,Salitan,A suspicious wife follows her husband in Bali....,2024-02-16,231.5883,4.714,7
12,1604143,나는 신혼 너는 재혼,,2021-08-12,274.1095,0.000,0
13,1103473,KD – The Devil,"In the early 1970s, a petty criminal Kaali unw...",2026-04-30,207.3802,7.500,2
14,1523145,Your Heart Will Be Broken,High school student Polina is saved from bully...,2026-03-26,254.0422,6.913,92
15,11012,Damage,The life of a respected British politician at ...,1992-12-02,184.6617,6.600,689
16,1304313,Lee Cronin's The Mummy,The young daughter of a journalist disappears ...,2026-04-15,168.1853,8.048,1861
17,912378,Dridam,A police officer arrives at a seemingly peacef...,2026-05-08,175.7922,7.000,1
18,454639,Masters of the Universe,"After being separated for 15 years, the Sword ...",2026-06-03,152.4585,7.300,236
19,1280738,The Furious,After Wang Wei's daughter is kidnapped by a cr...,2026-06-10,173.2088,8.100,39

In [21]:
df = pd.DataFrame() 
# step 2: mai ab ek Loop Chala raha hun 
for i in range(1, 429):
    # har baar loop ke ander mai es url pe hi karunga 
    response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=9c3510b4224a5c362c701d95238b950d&language=en-US&page={}'.format(i))   # matlb jo bhi i ka value honga wahi mera page number honga theek 
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity','vote_average', 'vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)